feature: add market version to allow disabling markets
NibiruChain/nibiru pull request #1559
Opened 2023-08-28 13:00 UTC by jgimeno

# Description

What does this PR do?

# Purpose

Why is this PR important?

2023-08-30 21:43 UTC, matthiasmatt reviewed
![image](https://github.com/NibiruChain/nibiru/assets/97468149/5545e67b-7bd1-411c-8a43-83407154e8a7)
Sonarcloud would be blocking this PR because of duplicated code in the pb.go file??

2023-09-08 20:04 UTC, jgimeno commented on x/common/testutil/genesis/perp_genesis.go
> +				Version:                         1,
I prefer the one given that 0 is the typical default value in proto

2023-09-08 20:19 UTC, jgimeno commented
Let's be careful with this one, so we don't forget any edge case.

2023-09-13 06:46 UTC, Unique-Divine requested changes
Review up to `module/abci.go`. Will continue going through the rest after I wake up in the morning

2023-09-13 12:05 UTC, jgimeno commented on x/perp/v2/keeper/admin.go
> +		Version:         1,
good catch!

2023-09-13 12:20 UTC, jgimeno commented on x/perp/v2/keeper/admin.go
> +		Version:         1,
fixed and added test to cover it.

2023-09-13 12:25 UTC, jgimeno commented on x/perp/v2/keeper/amm.go
> +	k.AMMs.Insert(ctx, collections.Join(pair, amm.Version), amm)
I agree in part, in theory entities should not know about implementation details of the other layer. In this case the persistence (keeper in our case) but i can do a convenience method in the keeper.

2023-09-13 14:05 UTC, jgimeno commented on x/perp/v2/keeper/hooks.go
> +		// TODO (reviewer): this needs to be fixed for only enabled markets
I think is not needed given we already know if it is disabled

2023-09-19 01:40 UTC, Unique-Divine approved these changes

2023-09-19 01:42 UTC, Unique-Divine approved these changes

2023-09-19 01:42 UTC, merged