fix: remove all stringer for proto types
NibiruChain/nibiru pull request #1874
Opened 2024-05-14 18:07 UTC by matthiasmatt

As per https://docs.cosmos.network/v0.50/build/migrations/upgrading#stringer, remove the stringer from the gogo proto.

For TD denoms, I had to create a pretty print for the "tf/contract_address/denom" logic.

2024-05-15 04:39 UTC, Unique-Divine requested changes

2024-05-15 04:39 UTC, Unique-Divine commented on x/tokenfactory/types/state.go
I think it'd make more sense to put the implementation inside `Denom` and call `DenomStr` everywhere rather than `PrettyString` because it's not so much a pretty print as it is the default string representation.

Then you'd end up with 
```go
func (tfd TFDenom) DenomStr() string {
	return DenomStr(tfd.Denom())
}

func (tfd TFDenom) Denom() DenomStr {
	return fmt.Sprintf("tf/%s/%s", tfd.Creator, tfd.Subdenom)
}
```

2024-05-15 11:37 UTC, matthiasmatt commented on x/tokenfactory/types/state.go
Why not Denom directly? what does denomstr bring?

2024-05-20 11:29 UTC, Unique-Divine approved these changes

2024-05-20 11:29 UTC, merged